/**
 * @fileoverview InfoCoreProvider 模块统一导出。
 */

// access 层
export { InfoCoreAccess } from './access/InfoCoreAccess';

// infrastructure 层
export { InfoCoreSchemaInitializer } from './infrastructure/InfoCoreSchemaInitializer';

// domain 层类型
export {
  InfoCoreContext,
  SaveInfoInput,
  SaveInfoOutput,
  PinInfoInput,
  PinInfoOutput,
  ProcessInfoInput,
  VectorInfoOutput,
  TagInfoOutput,
  SummaryInfoOutput,
  KeywordInfoOutput,
  GraphTagInput,
  GraphTagOutput,
  RebuildCooccurGraphInput,
  RebuildCooccurGraphOutput,
  LastNInfoInput,
  LastNInfoOutput,
  GraphNInfoInput,
  GraphNInfoOutput,
  SimilarKInfoInput,
  SimilarKInfoOutput,
  KeywordKInfoInput,
  KeywordKInfoOutput,
  RelationKInfoInput,
  RelationKInfoOutput,
  GraphInfoInput,
  GraphInfoOutput,
  SoCitationEdgesInput,
  SoCitationEdgesOutput,
  DelInfoGraphInput,
  DelInfoGraphOutput,
  ClearGraphInput,
  ClearGraphOutput,
  RebuildCitationGraphInput,
  RebuildCitationGraphOutput,
  ContextInfoInput,
  ContextInfoOutput,
  SoContextByWorkInput,
  SoContextByWorkOutput,
  SoInfoTagConfigInput,
  SoInfoTagConfigOutput,
  UpdateInfoTagConfigInput,
  UpdateInfoTagConfigOutput,
  SoInfoSummaryConfigInput,
  SoInfoSummaryConfigOutput,
  UpdateInfoSummaryConfigInput,
  UpdateInfoSummaryConfigOutput,
  SoInfoConfigInput,
  SoInfoConfigOutput,
  UpdateInfoConfigInput,
  UpdateInfoConfigOutput,
  SoInfoVectorConfigInput,
  SoInfoVectorConfigOutput,
  UpdateInfoVectorConfigInput,
  UpdateInfoVectorConfigOutput,
  SoInfoContextConfigInput,
  SoInfoContextConfigOutput,
  UpdateInfoContextConfigInput,
  UpdateInfoContextConfigOutput,
  DelInfoInput,
  DelInfoOutput,
  UpdateInfoInput,
  UpdateInfoOutput,
  DelInfoByWorkInput,
  DelInfoByWorkOutput,
  // ===== 新增（2026-09-15 记忆集中）：会话级记忆删除（info_context_source / GraphDB 级联）=====
  DelInfoBySessionInput,
  DelInfoBySessionOutput,
  ExistInfoInput,
  ExistInfoOutput,
  INFO_RAW_TABLE,
  INFO_CONTEXT_SOURCE_TABLE,
  INFO_VECTOR_TABLE,
  INFO_TAG_TABLE,
  INFO_TAG_VECTOR_TABLE,
  INFO_SUMMARY_TABLE,
  INFO_KEYWORD_TABLE,
  INFO_TAG_CONFIG_TABLE,
  INFO_SUMMARY_CONFIG_TABLE,
  INFO_CONFIG_TABLE,
  INFO_VECTOR_CONFIG_TABLE,
  INFO_CONTEXT_CONFIG_TABLE,
  DEFAULT_SUMMARY_THRESHOLD,
  DEFAULT_SUMMARY_INFO_TYPES,
} from './domain/types';

export type {
  InfoRawRecord,
  InfoVectorRecord,
  InfoTagRecord,
  InfoTagVectorRecord,
  InfoSummaryRecord,
  InfoKeywordRecord,
  InfoTagConfigRecord,
  InfoSummaryConfigRecord,
  InfoConfigRecord,
  InfoVectorConfigRecord,
  InfoContextConfigRecord,
  ContextCollectionSource,
  ContextInfoItem,
  ContextInfoCategories,
  ContextSourceIdMap,
  ContextContentMap,
  ContextAttributeMap,
  ContextInfoAttribute,
} from './domain/types';
