import Database from 'better-sqlite3';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  createWriterAgentService,
  WriterAgentService,
  WriteInput, WriteContext, WriteOutput,
  SaveUserProfileInput, SaveUserProfileContext, SaveUserProfileOutput,
  GetUserProfileInput, GetUserProfileContext, GetUserProfileOutput,
  ConfigWriterAgentInput, ConfigWriterAgentContext, ConfigWriterAgentOutput,
} from '../../src/agent/WriterAgent/WriterAgent';
import type { ChatCompletionRequest } from '../../src/base/LLMWrapper';

let db: Database.Database;
let service: WriterAgentService;
let mockLlmService: { chatCompletion: ReturnType<typeof vi.fn> };

beforeEach(() => {
  db = new Database(':memory:');
  mockLlmService = {
    chatCompletion: vi.fn().mockResolvedValue({
      choices: [{ message: { content: 'This is a generated response.' } }],
      usage: { totalTokens: 50 },
    }),
  };
  service = createWriterAgentService(db, mockLlmService as any);
});

afterEach(() => {
  db.close();
});

function makeAgentResults(count = 2) {
  const results: { agent_id: string; task_content: string; result: string }[] = [];
  for (let i = 0; i < count; i++) {
    results.push({
      agent_id: `agent-${i}`,
      task_content: `Task ${i}: analysis`,
      result: `Result for task ${i}`,
    });
  }
  return results;
}

function makeWriteInput(overrides: Partial<WriteInput> = {}) {
  return new WriteInput({
    work_id: 'work-1',
    interact_id: 'interact-1',
    user_query: 'What is the weather today?',
    agent_results: makeAgentResults(),
    ...overrides,
  });
}

// ============================================================================
// write
// ============================================================================
describe('WriterAgentService.write', () => {
  it('TC-WA-001: basic write with agent_results calls LLM and returns response in MARKDOWN', async () => {
    const input = makeWriteInput();
    const context = new WriteContext();
    const output = new WriteOutput();

    const result = await service.write(input, context, output);

    expect(result).toBe(true);
    expect(output.response).toBe('This is a generated response.');
    expect(output.response_format).toBe('MARKDOWN');
    expect(mockLlmService.chatCompletion).toHaveBeenCalledTimes(1);

    const req = mockLlmService.chatCompletion.mock.calls[0][0] as ChatCompletionRequest;
    expect(req.messages).toHaveLength(2);
    expect(req.response_format).toBeUndefined();
    expect(req.messages[0].role).toBe('system');
    expect(req.messages[1].role).toBe('user');
    expect(req.messages[1].content).toContain('What is the weather today?');
    expect(req.messages[1].content).toContain('Task 0: analysis');
    expect(req.messages[1].content).toContain('Result for task 0');
    expect(req.messages[1].content).toContain('Task 1: analysis');
    expect(req.messages[1].content).toContain('Result for task 1');
  });

  it('TC-WA-002: write with empty agent_results calls LLM with fallback results text', async () => {
    const input = makeWriteInput({ agent_results: [] });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    expect(output.response).toBe('This is a generated response.');
    expect(mockLlmService.chatCompletion).toHaveBeenCalledTimes(1);

    const req = mockLlmService.chatCompletion.mock.calls[0][0] as ChatCompletionRequest;
    expect(req.messages[1].content).toContain('No results available.');
  });

  it('TC-WA-003: write when LLM returns empty content uses resultsText as fallback', async () => {
    mockLlmService.chatCompletion.mockResolvedValueOnce({
      choices: [{ message: { content: '' } }],
      usage: { totalTokens: 0 },
    });

    const input = makeWriteInput({ agent_results: [] });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    expect(output.response).toBe('No results available.');
    expect(output.token_usage).toBe(0);
  });

  it('TC-WA-004: write without llmService uses fallback response', async () => {
    const svc = createWriterAgentService(db);
    const input = makeWriteInput();
    const context = new WriteContext();
    const output = new WriteOutput();

    const result = await svc.write(input, context, output);

    expect(result).toBe(true);
    expect(output.response).toContain('## What is the weather today?');
    expect(output.response).toContain('### Task 0: analysis');
    expect(output.response).toContain('Result for task 0');
    expect(output.response).toContain('Generated by WriterAgent');
    expect(output.response_format).toBe('MARKDOWN');
  });

  it('TC-WA-005: write without llmService and without agent_results uses fallback with defaults', async () => {
    const svc = createWriterAgentService(db);
    const input = makeWriteInput({ agent_results: [] });
    const context = new WriteContext();
    const output = new WriteOutput();

    await svc.write(input, context, output);

    expect(output.response).toContain('## What is the weather today?');
    expect(output.response).toContain('No results available.');
    expect(output.response).toContain('Generated by WriterAgent');
  });

  it('TC-WA-006: write sets elapsed_ms and token_usage on output', async () => {
    const input = makeWriteInput();
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    expect(typeof output.elapsed_ms).toBe('number');
    expect(output.elapsed_ms!).toBeGreaterThanOrEqual(0);
    expect(output.token_usage).toBe(50);
  });

  it('TC-WA-007: custom user_preferences override default style in LLM system prompt', async () => {
    const input = makeWriteInput({
      user_preferences: { style: 'creative', language: 'en-US', depth: 'deep' },
    });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    expect(mockLlmService.chatCompletion).toHaveBeenCalledTimes(1);
    const req = mockLlmService.chatCompletion.mock.calls[0][0] as ChatCompletionRequest;
    const systemMsg = req.messages.find(m => m.role === 'system')!.content;

    expect(systemMsg).toContain('Style: creative');
    expect(systemMsg).toContain('Language: en-US');
    expect(systemMsg).toContain('Depth: deep');
    expect(systemMsg).toContain('Write creatively with engaging language.');
  });

  it('TC-WA-008: partial user_preferences fill defaults for unspecified fields', async () => {
    const input = makeWriteInput({
      user_preferences: { style: 'concise' },
    });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    const req = mockLlmService.chatCompletion.mock.calls[0][0] as ChatCompletionRequest;
    const systemMsg = req.messages.find(m => m.role === 'system')!.content;

    expect(systemMsg).toContain('Style: concise');
    expect(systemMsg).toContain('Language: zh-CN');
    expect(systemMsg).toContain('Depth: medium');
    expect(systemMsg).toContain('Format: MARKDOWN');
    expect(systemMsg).toContain('Be concise and to the point');
  });

  it('TC-WA-009: LLM call fails falls back to buildFallbackResponse', async () => {
    mockLlmService.chatCompletion.mockRejectedValueOnce(new Error('LLM timeout'));

    const input = makeWriteInput();
    const context = new WriteContext();
    const output = new WriteOutput();

    const result = await service.write(input, context, output);

    expect(result).toBe(true);
    expect(output.response).toContain('## What is the weather today?');
    expect(output.response).toContain('### Task 0: analysis');
    expect(output.response).toContain('Generated by WriterAgent');
    expect(output.token_usage).toBe(0);
    expect(output.response_format).toBe('MARKDOWN');
  });

  it('TC-WA-010: LLM call fails with empty agent_results fills fallback', async () => {
    mockLlmService.chatCompletion.mockRejectedValueOnce(new Error('API error'));

    const input = makeWriteInput({ agent_results: [] });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    expect(output.response).toContain('No results available.');
    expect(output.response).toContain('Generated by WriterAgent');
    expect(output.token_usage).toBe(0);
  });

  it('TC-WA-011: user_query can be empty string', async () => {
    const input = makeWriteInput({ user_query: '' });
    const context = new WriteContext();
    const output = new WriteOutput();

    await service.write(input, context, output);

    const req = mockLlmService.chatCompletion.mock.calls[0][0] as ChatCompletionRequest;
    expect(req.messages[1].content).toContain('User question: ');
  });
});

// ============================================================================
// saveUserProfile
// ============================================================================
describe('WriterAgentService.saveUserProfile', () => {
  it('TC-WA-012: first save creates record with all fields', () => {
    const input = new SaveUserProfileInput({
      session_id: 'session-1',
      language: 'en-US',
      style: 'detailed',
      depth: 'deep',
      format: 'JSON',
      additional_preferences: '{"tone":"formal"}',
    });
    const context = new SaveUserProfileContext();
    const output = new SaveUserProfileOutput();

    const result = service.saveUserProfile(input, context, output);

    expect(result).toBe(true);

    const row = db.prepare('SELECT * FROM writer_agent_user_profile WHERE session_id = ?').get('session-1') as Record<string, unknown>;
    expect(row).toBeDefined();
    expect(row.session_id).toBe('session-1');
    expect(row.language).toBe('en-US');
    expect(row.style).toBe('detailed');
    expect(row.depth).toBe('deep');
    expect(row.format).toBe('JSON');
    expect(row.additional_preferences).toBe('{"tone":"formal"}');
  });

  it('TC-WA-013: upsert updates existing record, only specified fields change', () => {
    const input1 = new SaveUserProfileInput({
      session_id: 'session-2',
      language: 'zh-CN',
      style: 'clear',
      depth: 'medium',
      format: 'MARKDOWN',
      additional_preferences: '{}',
    });
    service.saveUserProfile(input1, new SaveUserProfileContext(), new SaveUserProfileOutput());

    const input2 = new SaveUserProfileInput({
      session_id: 'session-2',
      style: 'creative',
    });
    const output2 = new SaveUserProfileOutput();
    service.saveUserProfile(input2, new SaveUserProfileContext(), output2);

    const row = db.prepare('SELECT * FROM writer_agent_user_profile WHERE session_id = ?').get('session-2') as Record<string, unknown>;
    expect(row.style).toBe('creative');
    expect(row.language).toBe('zh-CN');
    expect(row.depth).toBe('medium');
    expect(row.format).toBe('MARKDOWN');
    expect(row.additional_preferences).toBe('{}');
  });

  it('TC-WA-014: upsert can update additional_preferences independently', () => {
    const input1 = new SaveUserProfileInput({
      session_id: 'session-ap',
      language: 'zh-CN',
      style: 'clear',
      depth: 'shallow',
      format: 'TEXT',
    });
    service.saveUserProfile(input1, new SaveUserProfileContext(), new SaveUserProfileOutput());

    const input2 = new SaveUserProfileInput({
      session_id: 'session-ap',
      additional_preferences: '{"new":"val"}',
    });
    service.saveUserProfile(input2, new SaveUserProfileContext(), new SaveUserProfileOutput());

    const row = db.prepare('SELECT * FROM writer_agent_user_profile WHERE session_id = ?').get('session-ap') as Record<string, unknown>;
    expect(row.additional_preferences).toBe('{"new":"val"}');
    expect(row.language).toBe('zh-CN');
  });

  it('TC-WA-015: empty session_id returns false', () => {
    const input = new SaveUserProfileInput({
      session_id: '',
      language: 'en-US',
    });
    const context = new SaveUserProfileContext();
    const output = new SaveUserProfileOutput();

    const result = service.saveUserProfile(input, context, output);

    expect(result).toBe(false);
  });
});

// ============================================================================
// getUserProfile
// ============================================================================
describe('WriterAgentService.getUserProfile', () => {
  it('TC-WA-016: query existing profile returns correct fields', () => {
    db.prepare(`INSERT INTO writer_agent_user_profile
      (id, created, updated, session_id, language, style, depth, format, additional_preferences)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .run('id-1', Date.now(), Date.now(), 'session-q1', 'en-US', 'concise', 'shallow', 'TEXT', '{"key":"value"}');

    const input = new GetUserProfileInput({ session_id: 'session-q1' });
    const context = new GetUserProfileContext();
    const output = new GetUserProfileOutput();

    const result = service.getUserProfile(input, context, output);

    expect(result).toBe(true);
    expect(output.user_profile).toBeDefined();
    expect(output.user_profile!.session_id).toBe('session-q1');
    expect(output.user_profile!.language).toBe('en-US');
    expect(output.user_profile!.style).toBe('concise');
    expect(output.user_profile!.depth).toBe('shallow');
    expect(output.user_profile!.format).toBe('TEXT');
    expect(output.user_profile!.additional_preferences).toBe('{"key":"value"}');
  });

  it('TC-WA-017: query non-existing profile returns default', () => {
    const input = new GetUserProfileInput({ session_id: 'nonexistent' });
    const context = new GetUserProfileContext();
    const output = new GetUserProfileOutput();

    const result = service.getUserProfile(input, context, output);

    expect(result).toBe(true);
    expect(output.user_profile).toEqual({
      language: 'zh-CN',
      style: 'clear',
      depth: 'medium',
      format: 'MARKDOWN',
    });
  });

  it('TC-WA-018: additional_preferences saved and retrieved correctly (null case)', () => {
    db.prepare(`INSERT INTO writer_agent_user_profile
      (id, created, updated, session_id, language, style, depth, format, additional_preferences)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .run('id-null', Date.now(), Date.now(), 'session-null', 'zh-CN', 'clear', 'medium', 'MARKDOWN', null);

    const input = new GetUserProfileInput({ session_id: 'session-null' });
    const context = new GetUserProfileContext();
    const output = new GetUserProfileOutput();

    service.getUserProfile(input, context, output);

    expect(output.user_profile!.additional_preferences).toBeNull();
  });
});

// ============================================================================
// configWriterAgent
// ============================================================================
describe('WriterAgentService.configWriterAgent', () => {
  function getConfig(): Record<string, unknown> {
    return db.prepare('SELECT * FROM writer_agent_config LIMIT 1').get() as Record<string, unknown>;
  }

  it('TC-WA-019: initial config has expected defaults', () => {
    const config = getConfig();
    expect(config.write_prompt_template_id).toBe('');
    expect(config.default_language).toBe('zh-CN');
    expect(config.default_style).toBe('clear');
    expect(config.default_depth).toBe('medium');
    expect(config.default_format).toBe('MARKDOWN');
  });

  it('TC-WA-020: configWriterAgent returns defaults in output when called with no overrides', () => {
    const input = new ConfigWriterAgentInput({});
    const context = new ConfigWriterAgentContext();
    const output = new ConfigWriterAgentOutput();

    const result = service.configWriterAgent(input, context, output);

    expect(result).toBe(true);
    expect(output.write_prompt_template_id).toBe('');
    expect(output.default_language).toBe('zh-CN');
    expect(output.default_style).toBe('clear');
    expect(output.default_depth).toBe('medium');
    expect(output.default_format).toBe('MARKDOWN');
  });

  it('TC-WA-021: update all valid fields persists correctly', () => {
    const input = new ConfigWriterAgentInput({
      write_prompt_template_id: 'tmpl-abc',
      default_language: 'en-US',
      default_style: 'creative',
      default_depth: 'deep',
      default_format: 'JSON',
    });
    const output = new ConfigWriterAgentOutput();

    const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), output);

    expect(result).toBe(true);
    expect(output.write_prompt_template_id).toBe('tmpl-abc');
    expect(output.default_language).toBe('en-US');
    expect(output.default_style).toBe('creative');
    expect(output.default_depth).toBe('deep');
    expect(output.default_format).toBe('JSON');

    const config = getConfig();
    expect(config.write_prompt_template_id).toBe('tmpl-abc');
    expect(config.default_language).toBe('en-US');
    expect(config.default_style).toBe('creative');
    expect(config.default_depth).toBe('deep');
    expect(config.default_format).toBe('JSON');
  });

  it('TC-WA-022: partial update changes only specified fields', () => {
    const input1 = new ConfigWriterAgentInput({
      write_prompt_template_id: 'tmpl-initial',
      default_language: 'fr',
      default_style: 'detailed',
      default_depth: 'shallow',
      default_format: 'TEXT',
    });
    service.configWriterAgent(input1, new ConfigWriterAgentContext(), new ConfigWriterAgentOutput());

    const input2 = new ConfigWriterAgentInput({
      default_language: 'ja',
      default_style: 'concise',
    });
    const output2 = new ConfigWriterAgentOutput();
    service.configWriterAgent(input2, new ConfigWriterAgentContext(), output2);

    expect(output2.default_language).toBe('ja');
    expect(output2.default_style).toBe('concise');

    const config = getConfig();
    expect(config.default_language).toBe('ja');
    expect(config.default_style).toBe('concise');
    expect(config.write_prompt_template_id).toBe('tmpl-initial');
    expect(config.default_depth).toBe('shallow');
    expect(config.default_format).toBe('TEXT');
  });

  it('TC-WA-023: invalid style returns false and does not persist', () => {
    const before = getConfig();

    const input = new ConfigWriterAgentInput({ default_style: 'invalid-style' });
    const output = new ConfigWriterAgentOutput();

    const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), output);

    expect(result).toBe(false);

    const after = getConfig();
    expect(after.default_style).toBe(before.default_style);
  });

  it('TC-WA-024: invalid depth returns false and does not persist', () => {
    const before = getConfig();

    const input = new ConfigWriterAgentInput({ default_depth: 'ultra-deep' });
    const output = new ConfigWriterAgentOutput();

    const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), output);

    expect(result).toBe(false);

    const after = getConfig();
    expect(after.default_depth).toBe(before.default_depth);
  });

  it('TC-WA-025: invalid format returns false and does not persist', () => {
    const before = getConfig();

    const input = new ConfigWriterAgentInput({ default_format: 'XML' });
    const output = new ConfigWriterAgentOutput();

    const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), output);

    expect(result).toBe(false);

    const after = getConfig();
    expect(after.default_format).toBe(before.default_format);
  });

  it('TC-WA-026: all valid style values accepted', () => {
    for (const style of ['clear', 'concise', 'detailed', 'creative']) {
      const input = new ConfigWriterAgentInput({ default_style: style });
      const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), new ConfigWriterAgentOutput());
      expect(result).toBe(true);
    }
  });

  it('TC-WA-027: all valid depth values accepted', () => {
    for (const depth of ['shallow', 'medium', 'deep']) {
      const input = new ConfigWriterAgentInput({ default_depth: depth });
      const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), new ConfigWriterAgentOutput());
      expect(result).toBe(true);
    }
  });

  it('TC-WA-028: all valid format values accepted', () => {
    for (const format of ['TEXT', 'MARKDOWN', 'JSON']) {
      const input = new ConfigWriterAgentInput({ default_format: format });
      const result = service.configWriterAgent(input, new ConfigWriterAgentContext(), new ConfigWriterAgentOutput());
      expect(result).toBe(true);
    }
  });
});
